jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Intalling AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: npm install && npm run build
      - run: aws s3 sync ./build s3://react-s3-ci

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy
